inherit_gem:
  rubocop-github:
    - config/default.yml

AllCops:
  NewCops: enable
  Exclude:
    - vendor/**/*
    - node_modules/**/*
    - _site/**/*
    - .jekyll-cache/**/* 
    - Gemfile.lock

Layout/LineLength:
  Enabled: false
