#!/usr/bin/env sh
set -e

echo "Installing Bundler and project gems..."
gem install bundler
bundle install

echo "Building Jekyll site..."
bundle exec jekyll build

echo "Running HTMLProofer..."
set +e
bundle exec htmlproofer ./_site || echo "HTMLProofer failed, but continuing..."
set -e

echo "Running RuboCop..."
bundle exec rubocop -D --config .rubocop.yml
