#!/usr/bin/env ruby
# frozen_string_literal: true
require "w3c_validators"

def validator_for(file)
  case File.extname(file)
  when ".html" then W3CValidators::NuValidator.new
  when ".css"  then W3CValidators::CSSValidator.new
  end
end

def validate(file)
  puts "Checking #{file}..."
  path = File.expand_path("../_site/#{file}", __dir__)
  v = validator_for(file)
  return puts "Skipping #{file}, no validator" unless v

  results = v.validate_file(path)
  if results.errors.empty?
    puts "Valid!"
  else
    results.errors.each { |err| puts err }
    exit 1
  end
end

validate "Commissions.html"
validate "Contact.html"
validate "Guides.html"
validate "index.html"
validate "ProtogenFiles.html"
validate "Software.html"
validate "Terms.html"
validate File.join("assets", "css", "style.css")
